name: Java CI add binary

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
      - uses: AButler/upload-release-assets@v2.0
        with:
          files: 'missilewars-plugins/target/MissileWars-*.jar;'
          repo-token: ${{ secrets.GITHUB_TOKEN }}